const lessonTitle = "曼德拉的番茄";

const lessonData = [
    // 正文第 1 段
    ["1964", "", "", ""], // 👈 阿拉伯数字：分开且留空
    ["年", "nián", "year", "tahun"],
    ["，", "", "", ""],
    ["罗本岛监狱", "luó běn dǎo jiān yù", "Robben Island Prison", "Penjara Pulau Robben"],
    ["又", "yòu", "again", "pula kembali"],
    ["来了一位", "lái le yí wèi", "came a (honorific for person)", "datang seorang"],
    ["新犯人", "xīn fàn rén", "new prisoner", "banduan baru"],
    ["。", "", "", ""],
    ["像", "xiàng", "like / resembles", "bagaikan / seperti"],
    ["其他犯人", "qí tā fàn rén", "other prisoners", "banduan-banduan yang lain"],
    ["一样", "yí yàng", "the same", "sama sahaja"],
    ["，", "", "", ""],
    ["他一进门", "tā yī jìn mén", "as soon as he entered door", "dia sebaik sahaja melangkah masuk pintu"],
    ["就被换上了", "jiù bèi huàn shàng le", "then was changed into", "terus ditukarkan dipakaikan baju"],
    ["专业的", "zhuān yè de", "professional / specialized", "yang khas punya"],
    ["囚服", "qiú fú", "prison uniform", "pakaian banduan"],
    ["，", "", "", ""],
    ["上面写着", "shàng miàn xiě zhe", "written on top", "di atasnya tertulis perkataan"],
    ["“第", "dì", "the (prefix for ordinal numbers)", "yang ke-"], // 👈 中文前缀：保留拼音翻译
    ["466", "", "", ""], // 👈 阿拉伯数字：分开且留空
    ["号”", "hào", "number", "nombor"],
    ["。", "", "", ""],
    ["他是一个", "tā shì yí gè", "He was a", "Dia merupakan seorang"], // 👈 中文数字“一个”：不分开，填满
    ["政治犯", "zhèng zhì fàn", "political prisoner", "banduan politik"],
    ["，", "", "", ""],
    ["被推进了", "bèi tuī jìn le", "was pushed into", "telah ditolak masuk ke dalam"],
    ["一个", "yí gè", "a", "sebuah"], // 👈 中文数字“一个”：不分开，填满
    ["不足", "bù zú", "less than / insufficient", "tidak sampai / kurang daripada"],
    ["4.5", "", "", ""], // 👈 阿拉伯数字：分开且留空
    ["平方米", "píng fāng mǐ", "square meters", "meter persegi"],
    ["的", "de", "particle", "punya"],
    ["单人牢房", "dān rén láo fáng", "solitary cell", "sel penjara seorang diri"],
    ["。", "", "", ""],
    ["从此", "cóng cǐ", "From then on", "Semenjak dari saat itu kelak"],
    ["，", "", "", ""],
    ["他过上了", "tā guò shàng le", "he lived a life of", "dia mula menjalani riwayat hidup yang"],
    ["“暗无天日”", "àn wú tiān rì", "complete darkness", "gelap-gelita tanpa sinar matahari"],
    ["的", "de", "particle", "punya"],
    ["生活", "shēng huó", "life", "kehidupan"],
    ["。", "", "", ""],
    ["他每天", "tā měi tiān", "He every day", "Dia setiap hari"],
    ["被囚禁", "bèi qiú jìn", "was imprisoned", "dikurung dipenjarakan"],
    ["23", "", "", ""], // 👈 阿拉伯数字：分开且留空
    ["个小时", "gè xiǎo shí", "hours", "jam"],
    ["，", "", "", ""],
    ["仅仅在", "jǐn jǐn zài", "only at", "sekadar sekadar pada waktu"],
    ["上午", "shàng wǔ", "morning", "pagi hari"],
    ["和", "hé", "and", "dan"],
    ["下午", "xià wǔ", "afternoon", "petang hari"],
    ["才有", "cái yǒu", "only then had", "barulah menikmati kesempatan ada"],
    ["半个小时", "bàn gè xiǎo shí", "half an hour", "setengah jam"], // 👈 中文数字“半个”：不分开，填满
    ["的", "de", "particle", ""],
    ["放风时间", "fàng fēng shí jiān", "recreation time", "masa keluar mengambil udara segar"],
    ["，", "", "", ""],
    ["所以", "suǒ yǐ", "therefore", "oleh yang demikian halnya"],
    ["，", "", "", ""],
    ["他几乎", "tā jī hū", "he almost", "dia boleh dikatakan hampir"],
    ["从来没有", "cóng lái méi yǒu", "never before", "sepanjang hayat tidak pernah"],
    ["见过", "jiàn guò", "seen", "melihat"],
    ["罗本岛监狱的", "luó běn dǎo jiān yù de", "Robben Island Prison's", "Penjara Pulau Robben punya"],
    ["太阳", "yáng guāng", "sun / sunlight", "cahaya matahari"],
    ["，", "", "", ""],
    ["也很少有", "yě hěn shǎo yǒu", "also rarely had", "malah tersangat jarang ada"],
    ["机会", "jī huì", "opportunity / chance", "peluang kesempatan untuk"],
    ["感受到", "gǎn shòu dào", "feel / perceive", "merasai menikmati"],
    ["窗外的", "chuāng wài de", "outside window's", "luar tingkap punya"],
    ["丝丝风声", "sī sī fēng shēng", "traces of wind sound", "hembusan sepoi-sepoi bunyi angin"],
    ["，", "", "", ""],
    ["能感知的", "néng gǎn zhī de", "could perceive's", "apa yang mampu dikesan rasa punya perkara"],
    ["只有", "zhǐ  yǒu", "only had", "hanya adalah semata-mata"],
    ["灰头土脸的", "huī tóu tǔ liǎn de", "disheveled and dirt-faced", "banduan yang comot sarat debu bumi punya"],
    ["囚犯", "qiú fàn", "prisoners", "banduan"],
    ["，", "", "", ""],
    ["还有", "hái yǒu", "and also had", "serta serta ada"],
    ["他们所发出的", "tā men suǒ fā chū de", "emitted by them", "apa yang dikeluarkan oleh mereka punya"],
    ["呻吟声", "shēn yín shēng", "groans / moans", "suara rintihan hiba kesakitan"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 2 段
    ["罗本岛监狱", "luó běn dǎo jiān yù", "Robben Island Prison", "Penjara Pulau Robben itu"],
    ["是个", "shì ge", "is a", "adalah merupakan sebuah"],
    ["阴森的", "yīn sēn de", "gloomy / grim", "dewan besar yang tersangat seram dan sunyi sepi"],
    ["殿堂", "diàn táng", "hall", "tempat"],
    ["，", "", "", ""],
    ["那里的", "nà lǐ de", "there's", "di sana punya tempat punya"],
    ["狱警", "yù jǐng", "prison guards", "polis penjara / warder"],
    ["动辄就", "dòng zhé jiù", "at every turn", "sikit-sikit asyik terus sahaja"],
    ["对囚犯们", "duì qiú fàn men", "towards prisoners", "terhadap banduan-banduan belaka"],
    ["挥起", "huī qǐ", "raised", "mengacungkan hayun naik up"],
    ["残酷的", "cán kù de", "cruel", "cemeti sebatan yang tersangat zalim kejam punya"],
    ["鞭子", "biān zi", "whips", "tali cemeti / sebatan rotan"],
    ["。", "", "", ""],
    ["已经记不清", "yǐ jīng jì bù qīng", "Cannot remember clearly", "Dah tidak mampu lagi nak ingat dengan jelas"],
    ["多少个日子", "duō shǎo gè rì zi", "how many days", "berapa banyak rangkaian hari masa"], // 👈 中文“多少个”：不分开，填满
    ["，", "", "", ""],
    ["他几乎每天", "tā jī hū měi tiān", "he almost every day", "dia boleh dikatakan hampir saban hari"],
    ["都目睹", "dōu mù dǔ", "witnessed with own eyes", "asyik menyaksikan sendiri melihat"],
    ["两个", "liǎng gè", "two", "dua orang"], // 👈 中文数字“两个”：不分开，填满
    ["狱警", "yù jǐng", "prison guards", "warder penjara"],
    ["拖着", "tuō zhe", "dragging", "sedang mengheret menyeret kaki"],
    ["一个", "yí gè", "a", "seorang"], // 👈 中文数字“一个”：不分开，填满
    ["犯人", "fàn rén", "prisoner", "banduan"],
    ["，", "", "", ""],
    ["死尸一样地", "sǐ shī yí yàng de", "corpse-like", "bagaikan mirip sesosok mayat mati belaka di"],
    ["从刑讯室", "cóng xíng xùn  shì", "from the interrogation room", "keluar dari bilik penyiksaan denda"],
    ["出来", "chū lái", "came out", "keluar mari"],
    ["，", "", "", ""],
    ["每次", "měi cì", "every time", "setiap kali kejadian"], // 👈 中文“每次”：不分开，填满
    ["都看得他", "dōu kàn de tā", "made him watch until", "sememangnya menyebabkan dia melihatnya sehingga"],
    ["义愤填膺", "yì fèn tián yīng", "filled with righteous indignation", "sarat dipenuhi rasa amat marah and benci atas kezaliman itu"],
    ["。", "", "", ""],
    ["他每一次", "tā mĕi yí cì", "He every single time", "Dia setiap kali jua"], // 👈 中文“每一次”：不分开，填满
    ["都想", "dōu xiǎng", "all wished to", "memang berazam berniat mahu"],
    ["改变", "gǎi biàn", "change", "mengubah membaiki"],
    ["监狱的", "jiān yũ de", "prison's", "keadaan penjara punya"],
    ["现状", "xiàn zhuàng", "current situation", "status quo / keadaan semasa sekarang"],
    ["，", "", "", ""],
    ["无奈的是", "wú nài de shì", "helplessly", "namun apa yang tersangat mendukacitakan adalah"],
    ["，", "", "", ""],
    ["身为", "shēn wéi", "as / being", "memandangkan kedudukan diri sebagai seorang"],
    ["“重犯”", "zhòng fàn", "heavy criminal", "banduan besar / banduan kelas berat"],
    ["的他", "de tā", "of him", "punya dia"],
    ["始终", "shǐ zhōng", "always", "sepanjang masa kekal lama"],
    ["没有机会", "méi yǒu jī huì", "had no opportunity", "langsung tidak berpeluang menikmati kesempatan"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 3 段
    ["后来", "hòu lái", "Later on", "Kemudian selepas itu kelak"],
    ["，", "", "", ""],
    ["他和", "tā hé", "he and", "dia bersama with"],
    ["众囚犯", "zhòng qiú fàn", "all the prisoners", "keseluruhan khalayak banduan yang lain"],
    ["被安排到", "bèi ān pái dào", "were arranged to go to", "telah diarah diaturkan pergi ke"],
    ["罗本岛监狱的", "luó bĕn dǎo jiān yù de", "Robben Island Prison's", "Penjara Pulau Robben punya"],
    ["采石场上", "cǎi shí chǎng shàng", "stone quarry top", "kawasan tapak kuari memecah batu gergasi atas"],
    ["去做苦工", "qù zuò kǔ gōng", "to do hard labor", "untuk menjalankan kerja buruh paksa yang amat perit"],
    ["，", "", "", ""],
    ["每天", "měi tiān", "every day", "saban hari"],
    ["在持枪看守的", "zài chí qiāng kān shǒu de", "under armed guards'", "di bawah kawalan warder yang memegang senapang punya"],
    ["监督下", "jiān dū xià", "supervision underneath", "pengawasan ketat di bawah"],
    ["拼命地", "pīn mìng de", "desperately", "berhempas-pulas bermati-matian"],
    ["搬运", "bān yùn", "transporting", "mengangkat mengangkut"],
    ["石头", "shí tou", "stones", "bongkah batu besar"],
    ["，", "", "", ""],
    ["动作稍慢", "dòng zuò shāo màn", "action slightly slow", "pergerakan kalau lambat sedikit sahaja"],
    ["就有", "jiù yǒu", "then had", "maka terus berdepan risiko ada"],
    ["被毒打的", "bèi dú dǎ de", "being severely beaten's", "dibelasah dipukul dengan tersangat kejam punya"],
    ["危险", "wēi xiǎn", "danger", "bahaya musibah"],
    ["。", "", "", ""],
    ["另外", "lìng wài", "In addition", "Ditambah pula selain daripada itu"],
    ["，", "", "", ""],
    ["所有的", "suǒ yǒu de", "all's", "keseluruhan belaka"],
    ["囚犯", "qiú fàn", "prisoners", "banduan itu"],
    ["只准备", "zhǐ zhǔn bèi", "only permitted to", "hanya dibenarkan sekadar"],
    ["逗留在", "dòu liú zài", "stay at", "berada menetap di dalam"],
    ["这个", "zhè ge", "this", "ini buah"],
    ["采石场里", "cǎi shí chǎng lǐ", "inside quarry", "kawasan jajaran kuari batu sahaja"],
    ["，", "", "", ""],
    ["一旦", "yí dàn", "once", "sekali sahaja sekiranya bertindak"],
    ["踏出", "tà chū", "step out of", "melangkah keluar merentasi"],
    ["采石场的", "cǎi shí chǎng de", "quarry's", "kuari batu punya"],
    ["边缘", "biān yuán", "edge / border", "garisan sempadan tepi"],
    ["，", "", "", ""],
    ["就会被", "jiù huì bèi", "then will be by", "pasti akan terus dikerjakan oleh pihak tentera"],
    ["无情地", "wú qíng de", "ruthlessly", "secara kejam tanpa belas kasihan"],
    ["射杀", "shè shā", "shot dead", "ditembak mati"],
    ["。", "", "", ""],
    ["由于", "yóu yú", "Due to / because", "Oleh kerana disebabkan"],
    ["石灰石", "shí huī shí", "limestone", "batuan batu kapur kuari"],
    ["在太阳的", "zài yáng guāng de", "under sun's", "di bawah sinaran cahaya matahari punya"],
    ["照射下", "zhào shè xià", "shining underneath", "pancaran suluhan di bawah"],
    ["具有", "jù yǒu", "possessed", "mempunyai sifat daya"],
    ["极强的", "jí qiáng de", "extremely strong", "pantulan yang tersangat kuat punya"],
    ["反光性", "fǎn guāng xìng", "reflectivity", "sifat memantulkan balik cahaya silau"],
    ["，", "", "", ""],
    ["长期在", "cháng qī zài", "long term inside", "dalam tempoh masa yang tersangat panjang di dalam"],
    ["这种环境下", "zhè zhǒng huán jìng xià", "this environment underneath", "keadaan sekitar sebegini rupa bawah"],
    ["生活的", "shēng huó de", "living's", "menjalani riwayat hidup"],
    ["他", "tā", "he", "dia"],
    ["，", "", "", ""],
    ["每天", "měi tiān", "every day", "saban hari suntuk"],
    ["看到的", "kàn jiàn de", "saw's", "apa yang dipandang oleh mata punya perkara"],
    ["只有", "zhǐ  yǒu", "only was", "hanya ada semata-mata"],
    ["刺眼的", "cì yǎn de", "glaring", "kilauan silau yang menyakitkan mata punya"],
    ["白色强光", "bái sè qiáng guāng", "white intense light", "pancaran cahaya putih yang tersangat terik"],
    ["，", "", "", ""],
    ["以至于", "yǐ zhì yú", "so that", "sehingga mengakibatkan menyebabkan"],
    ["他的", "tā de", "his", "dia punya"],
    ["视力", "shì lì", "eyesight", "daya penglihatan mata"],
    ["逐渐", "zhú jiàn", "gradually", "lama-kelamaan / perlahan-lahan"],
    ["下降", "xià jiàng", "declined", "merosot menjadi kabur turun"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 4 段
    ["虽然", "suī rán", "Although", "Walaupun semestinya sungguhpun"],
    ["它的", "tā de", "his", "dia punya jajaran"],
    ["视线", "shì xiàn", "line of vision", "pandangan mata kasar"],
    ["逐渐", "zhú jiàn", "gradually", "perlahan-lahan"],
    ["变得", "biàn de", "became", "bertukar menjadi semakin"],
    ["模糊", "mó hu", "blurred", "kabur kabur kelabu"],
    ["，", "", "", ""],
    ["而", "ér", "yet", "namun sebaliknya sebaliknya"],
    ["他的", "tā de", "his", "dia punya baki"],
    ["目光", "mù guāng", "gaze", "sorotan pandangan anak mata batin"],
    ["却", "què", "conversely", "tetap kekal"],
    ["炯炯有神", "jiǒng jiõng yǒu shén", "bright and piercing", "tajam bersinar-sinar sarat obor semangat"],
    ["。", "", "", ""],
    ["为了", "wèi le", "In order to", "Demi untuk tekad mahu"],
    ["改变", "gǎi biàn", "change", "mengubah membaiki"],
    ["这种", "zhè zhǒng", "this kind of", "keadaan nasib sebegini rupa punya"],
    ["悲惨的", "bēi cǎn de", "miserable", "tersangat tragis punya"],
    ["现状", "xiàn zhuàng", "current situation", "status quo semasa"],
    ["，", "", "", ""],
    ["他利用", "tā lì yòng", "he utilized", "dia menggunakan kesempatan peluang"],
    ["放风的", "fàng fēng de", "outdoor exercise's", "waktu bersiar-siar keluar mengambil udara segar punya"],
    ["机会", "jī huì", "opportunity", "kesempatan kelak"],
    ["，", "", "", ""],
    ["大胆地", "dàn dǎn de", "boldly", "dengan penuh berani gila-gilaan"],
    ["向监狱长", "xiàng jiān  yù zhǎng", "towards prison warden", "menghadap ke arah pengarah ketua penjara"],
    ["提出了", "tí chū le", "proposed", "mengemukakan mengutar"],
    ["自己的", "zì jǐ de", "oneself's", "diri own punya isi"],
    ["想法", "xiǎng fǎ", "idea", "buah fikiran cadangan"],
    ["：", "", "", ""],
    ["在监狱的", "zài jiān yù de", "inside prison's", "di dalam kawasan halaman penjara punya"],
    ["院子里", "yuàn zi lǐ", "inside the courtyard", "kawasan pekarangan tengah"],
    ["开辟", "kāi pì", "open up", "meneroka membuka tanah membuat"],
    ["一片", "yí piàn", "a piece of", "sejalur sebidang"], // 👈 中文数字“一片”：不分开，填满
    ["园子", "yuán zi", "garden", "tapak kebun kecil"],
    ["。", "", "", ""],
    ["哪知道", "nǎ zhī dào", "Who would have known", "Namun masakan tidak disangka-sangka langsung"],
    ["他的", "tā de", "his", "dia punya isi"],
    ["这一想法", "zhè yī xiǎng fǎ", "this single idea", "cadangan satu ini baru sahaja"],
    ["刚一出口", "gāng yī chū kǒu", "just left mouth", "terkeluar dari celah bibir"],
    ["，", "", "", ""],
    ["就被", "jiù bèi", "then was by", "terus sahaja ditindak oleh pihak"],
    ["监狱当局", "jiān  yù dāng jú", "prison authorities", "pihak pengurusan berkuasa penjara"],
    ["无情地", "wú qíng de", "ruthlessly", "secara zalim tanpa belas kasihan kekejaman"],
    ["否决了", "fǒu jué le", "rejected", "ditolak mentah-mentah / dibatalkan bulat-bulat"],
    ["。", "", "", ""],
    ["他并", "tā bìng", "He conversely", "Dia sebaliknya langsung jua"],
    ["没有灰心", "méi  yǒu huī xīn", "did not lose heart", "tidak patah semangat / tidak putus asa"],
    ["，", "", "", ""],
    ["几乎", "jī hū", "almost", "boleh dikatakan hampir"],
    ["一有机会", "yī jī huì", "as soon as had opportunity", "pantang pantang ada peluang sahaja kelak"],
    ["他就要", "tā jiù yào", "he then would", "dia pasti terus wajib akan"],
    ["把自己的", "bǎ zì jǐ de", "oneself's", "menyebabkan diri sendiri punya isi"],
    ["想法", "xiǎng fǎ", "idea", "cadangan fikiran itu"],
    ["说出来", "shuō chū lái", "speak out", "disuarakan dituturkan keluar mari"],
    ["，", "", "", ""],
    ["经过了", "jīng guò le", "passed through", "selepas merentasi melalui fasa jajaran"],
    ["无数次的", "wú shù cì de", "countless times of", "beratus-ratus kali penolakan punya"],
    ["否决", "fǒu jué", "rejections", "pembatalan dan penolakan mentah-mentah"],
    ["，", "", "", ""],
    ["大约过了", "dà yuē guò le", "approximately passed", "anggaran selang waktu masa merentasi jajaran"],
    ["五年", "wǔ nián", "five years", "5 tahun"], // 👈 中文数字“五年”：大获全胜不分开，填满拼音翻译！
    ["，", "", "", ""],
    ["他的", "tā de", "his", "dia punya tekad"],
    ["愿望", "yuàn wàng", "wish", "impian hasrat murni kehendak hati"],
    ["终于", "zhōng yú", "finally", "akhirnya kesudahannya berjaya jua"],
    ["实现了", "shí xiàn le", "realized", "menjadi kenyataan benaran tercapai"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 5 段
    ["监狱当局", "jiān  yù dāng jú", "The prison authorities", "Pihak pengurusan berkuasa tertinggi penjara itu"],
    ["同意了", "tóng yì le", "approved", "telah memberi lampu hijau bersetuju meluluskan"],
    ["在监狱墙脚的", "zài jiān  yù qiáng jiǎo de", "at the prison wall base's", "di bahagian kaki dinding tembok penjara punya"],
    ["一片", "yí piàn", "a stretch of", "sejalur sebidang tanah"], // 👈 中文数字“一片”：不分开，填满
    ["狭长地带", "xiá cháng dì dài", "narrow long strip of land", "kawasan zon laluan tanah yang tersangat sempit dan panjang"],
    ["供他", "gōng tā", "for him to", "untuk kegunaan dia mendatar"],
    ["开辟园子", "kāi pì yuán zi", "open up garden", "meneroka membuka tapak kebun sayur"],
    ["，", "", "", ""],
    ["并且", "bìng qiě", "and furthermore", "malah ditumpu ditambahkan pula kekaguman"],
    ["破天荒地", "pò tiān huāng de", "unprecedentedly", "buat julung-julung kalinya sepanjang sejarah keajaiban"],
    ["给他提供了", "gěi tā tí gōng le", "provided him with", "membekalkan menyerahkan kepada dia jajaran baki"],
    ["番茄", "fān qié", "tomatoes", "buah tomato"],
    ["、", "", "", ""],
    ["辣椒等", "là jiāo děng", "chili etc.", "cili padi dan sebagainya jenis"],
    ["蔬菜的", "shū cài de", "vegetables'", "sayur-sayuran punya"],
    ["种子", "zhǒng zǐ", "seeds", "biji benih tanaman"],
    ["。", "", "", ""],
    ["院子", "yuán zi", "The courtyard", "Kawasan pekarangan halaman itu"],
    ["是用", "shì yòng", "was by using", "sebenarnya adalah menggunakan kekerapan"],
    ["废渣", "fèi zhā", "waste residue", "sisa baki sisa buangan kuari batuan buruk"],
    ["垫起来的", "diàn qǐ lái de", "padded up's", "ditimbus dilapik dikambus naik up punya tanah gersang"],
    ["，", "", "", ""],
    ["为了", "wèi le", "in order to", "demi untuk membolehkan usaha"],
    ["开辟菜园", "kāi pì cài yuán", "open up vegetable garden", "meneroka membuka kebun sayur itu berjalan"],
    ["，", "", "", ""],
    ["他必须把", "tā bì xū bǎ", "he must", "dia wajib memaksakan diri menyebabkan jajaran"],
    ["大量的", "dà liàng de", "large amount of", "berlambak-lambak kuantiti gergasi punya"],
    ["石块", "shí kuài", "stone blocks", "bongkah ketul batu kuari"],
    ["挖出来", "wā chū lái", "dig out", "digali dicungkil keluar dari dalam tanah gersang"],
    ["，", "", "", ""],
    ["这样一来", "zhè yàng yī lái", "in this way", "apabila dilakukan sedemikian rupa perkara ini"],
    ["，", "", "", ""],
    ["植物", "zhí wù", "plants", "tumbuhan benih sayur hijau itu"],
    ["才有", "cái  yǒu", "only then had", "barulah akan menikmati kesempatan mempunyai"],
    ["足够的", "zú gòu de", "enough", "yang tersangat mencukupi"],
    ["生长空间", "shēng zhǎng kōng jiān", "growth space", "ruang tapak untuk membesar membiak"],
    ["。", "", "", ""],
    ["罗本岛监狱的", "luó bĕn dǎo jiān  yù de", "Robben Island Prison's", "Penjara Pulau Robben punya"],
    ["院子里", "yuàn zi lǐ", "courtyard within", "dalam pekarangan halaman tengah itu"],
    ["从此", "cóng cǐ", "from then on", "semenjak saat itu kelak"],
    ["多了一抹", "duō le  yì mǒ", "added a touch of", "telah bertambah hadir secalit satu sentuhan warna"], // 👈 中文数字“一抹”：不分开，填满
    ["动人的", "dòng  rén de", "moving", "hijau yang tersangat menawan jiwa"],
    ["绿色", "lǜ sè", "green", "warna hijau kehidupan"],
    ["。", "", "", ""],
    ["由于", "yóu yú", "Due to", "Namun sebaliknya adalah disebabkan oleh faktor"],
    ["气候的", "tiān qì de", "climate's", "keadaan cuaca dan iklim alam yang tersangat"],
    ["恶劣", "è liè", "harsh", "buruk dan gersang parah musibah"],
    ["，", "", "", ""],
    ["园子的", "yuán zi de", "garden's", "tapak kebun sayur itu punya buah"],
    ["第一茬", "dì yī chá", "first harvest", "pusingan hasil tuaian pusingan pertama"], // 👈 中文数字“第一茬”：不分开，填满
    ["收成", "shōu chéng", "harvest", "hasil pulangan tuaian rezeki"],
    ["并", "bìng", "conversely", "langsung nyata sekali sebenarnya"],
    ["不是很好", "bú shì hěn hǎo", "was not very good", "adalah kurang memuaskan"],
    ["，", "", "", ""],
    ["仅仅收获了", "jǐn jǐn shōu huò le", "only harvested", "sekadar sekaju menuai mendapat balik buah"],
    ["一篮子", "yì lán zi", "a basket of", "sebakul penuh buah"], // 👈 中文数字“一篮子”：不分开，填满
    ["不怎么红润的", "bù zěn me hóng rùn de", "not so rosy red", "tomato yang tidak brapa merah menyala semata-mata punya"],
    ["番茄", "fān qié", "tomatoes", "buah tomato"],
    ["他一个也", "tā yí gè yě", "He even a single one", "Dia walau sebiji pun buah tomato itu langsung"], // 👈 中文数字“一个”：不分开，填满
    ["舍不得吃", "shě bu dé chī", "grudged to eat", "tidak tegar hati / tidak sanggup nak makan telan sendiri"],
    ["，", "", "", ""],
    ["都分给了", "dōu fēn gěi le", "all distributed to", "sebaliknya habis semuanya diserahkan dibahagikan kepada"],
    ["自己的", "zì jǐ de", "oneself's", "diri own punya kumpulan rakan"],
    ["狱友", "yù yǒu", "prison cellmates", "rakan sepenjara rakan sekongkol"],
    ["和", "hé", "and", "dan juga"],
    ["狱警们", "yù jǐng men", "prison guards", "warder-warder polis penjara belaka"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 6 段
    ["罗本岛监狱的", "luó bĕn dǎo jiān  yù de", "Robben Island Prison's", "Keadaan harian Penjara Pulau Robben punya"],
    ["条件", "tiáo jiàn", "conditions", "fasiliti dan kedaifan persekitaran"],
    ["简直", "jiǎn zhí", "simply", "sebenarnya adalah benar-benar tersangat"],
    ["太艰苦了", "tài jiān kǔ le", "too hard", "memenatkan dan daif menderita parah gila gila"],
    ["，", "", "", ""],
    ["以至于", "yǐ zhì yú", "so that", "sehingga mengakibatkan menyebabkan hal"],
    ["能够吃到", "néng gòu chī dào", "being able to eat", "berupaya dapat makan menikmati buah"],
    ["这样的", "zhè yàng de", "this kind of", "tomato sebegini punya segar rupa"],
    ["番茄", "fān qié", "tomatoes", "buah tomato merah"],
    ["变成了", "biàn chéng le", "changed into", "telah bertambah bertukar menjadi sehelai"],
    ["一件", "yí jiàn", "a matter", "satu perkara"], // 👈 中文数字“一件”：不分开，填满
    ["奢侈的事情", "shē chǐ de  shì qing", "luxury matter", "perkara yang tersangat mewah gergasi"],
    ["。", "", "", ""],
    ["他一从", "tā yī cóng", "he as soon as from", "Dia sebaik sahaja balik melangkah keluar dari"], // 👈 中文数字“一”：不分开，填满
    ["采石场", "cǎi shí chǎng", "stone quarry", "kawasan kuari memecah batu gergasi"],
    ["回来", "huí lái", "returned", "pulang ke sel penjara"],
    ["就细心照料", "jiù xì xīn zhào liào", "then meticulously took care of", "terus mencurahkan tumpuan dengan tersangat teliti menjaga"],
    ["自己的", "zì jǐ de", "oneself's", "diri own punya kebun"],
    ["园子", "yuán zi", "garden", "tapak kebun sayur itu"],
    ["，", "", "", ""],
    ["他每天", "tā měi tiān", "he every day", "dia saban hari suntuk harian"],
    ["把全部心思", "bǎ quán bù xīn sī", "whole mind and thoughts", "menyebabkan keseluruhan sehabis-habis tumpuan akal fikiran"],
    ["都花在", "dōu huā zài", "all spent on", "habis dicurahkan diluangkan di atas"],
    ["自己的", "zì jǐ de", "oneself's", "diri own punya tapak"],
    ["园子上", "yuán zi shàng", "garden top", "kebun sayur atas jajaran"],
    ["。", "", "", ""],
    ["许多人", "xǔ duō rén", "Many people", "Ramai orang banduan keliling"], // 👈 中文数量“许多人”：不分开，填满
    ["都说他", "dōu shuō tā", "all said he", "pun asyik mendakwa menggelarkan dia"],
    ["是监狱里的", "shì jiān  yù lǐ de", "is inside prison's", "adalah merupakan tokoh pakar di dalam penjara punya"],
    ["“植物学家”", "zhí wù xué jiā", "botanist", "Ahli Botani (Pakar Tumbuhan)"],
    ["，", "", "", ""],
    ["而他自己", "ér wǒ zì jǐ", "and he himself", "manakala dia diri dia sendiri pula sebaliknya"],
    ["则把", "zé bǎ", "conversely object particle", "sebaliknya bertindak meletakkan pandangan menyebabkan jajaran"],
    ["那片园子", "nà piàn yuัน zi", "that stretch of garden", "sebidang kebun sayur itu"],
    ["看成了", "kàn chéng le", "regarded as", "dianggap dinilai sebagai sebuah"],
    ["自己的", "zì jǐ de", "oneself's", "diri own punya lubuk sanubari tempat"],
    ["心灵园地", "xīn líng yuán dì", "spiritual garden", "tapak tanah halaman tempat menenangkan jiwa"],
    ["。", "", "", ""],
    ["每当", "měi dāng", "Every time when", "Setiap kali apabila jajaran"],
    ["采石场上的", "cǎi shí chǎng shàng de", "on the stone quarry's", "di atas kuari memecah batu punya"],
    ["石灰石", "shí huī shí", "limestones", "batuan batu kapur kuari silau"],
    ["刺伤了", "cì shāng le", "stabled and hurt", "menyebabkan rasa tersangat pedih mencederakan"],
    ["他的", "tā de", "his", "dia punya sepasang"],
    ["眼睛", "yǎn jing", "eyes", "anak mata kasar"],
    ["，", "", "", ""],
    ["他就借", "jiù jiè", "he then borrowed", "dia terus menggunakan kesempatan pinjam pinjam waktu"],
    ["放风的", "fàng fēng de", "outdoor exercise's", "keluar mengambil udara segar punya"],
    ["时间", "shí jiān", "time", "tempoh masa jajaran"],
    ["回到", "huí dào", "returned to", "melangkah balik semula ke"],
    ["自己的", "zì jǐ de", "oneself's", "diri own punya kebun sayur"],
    ["园子", "yuán zi", "garden", "tapak kebun itu untuk"],
    ["望一望", "wàng yí wàng", "take a look", "memandang menjeling menatap sekilas sekejap"],
    ["。", "", "", ""],
    ["那样", "nà yàng", "That kind of", "Keadaan sedemikian sebegini punya"],
    ["一片", "yí piàn", "a stretch of", "sebidang panorama jajaran"], // 👈 中文数字“一片”：不分开，填满
    ["生命的绿", "shēng mìng de lǜ", "life's green", "warna hijau tanda riwayat kehidupan bertenaga"],
    ["在微风的", "zài wēi fēng de", "under gentle breeze's", "di bawah tiupan sepoi-sepoi bayu angin punya"],
    ["吹拂中", "chuī fú zhōng", "blowing underneath", "hembusan belai di dalam"],
    ["，", "", "", ""],
    ["轻轻摇曳", "qīng qīng yáo yè", "gently swaying", "sedang bergoyang-goyang melambai anggun dengan lemah lembut"],
    ["，", "", "", ""],
    ["红润可爱的", "hóng rùn kě ài de", "rosy red and lovely", "buah tomato yang merah menyala comet memikat hati punya"],
    ["西红柿", "xī hóng  shì", "tomatoes", "buah tomato merah segar bugar"],
    ["从绿叶中", "cóng lǜ yè zhōng", "from inside green leaves", "dari celah seliran daun-daun hijau di dalam"],
    ["探出头来", "tàn chū tóu lái", "poked head out", "mula menjelir menjenguk mengeluarkan kepala keluar mari"],
    ["。", "", "", ""],
    ["这片菜园", "zhè piàn cài yuán", "This stretch of vegetable garden", "Sebidang tapak kebun sayur ini jua"],
    ["缓解了", "huǎn jiě le", "relieved", "berjaya melegakan meredakan rasa pedih"],
    ["他眼睛的", "tā yǎn jing de", "his eyes'", "dia punya anak mata kasar punya"],
    ["疲劳", "pí láo", "fatigue", "keletihan lesu silap"],
    ["，", "", "", ""],
    ["也消解了", "yě xiāo jiě le", "also dissolved", "malah turut melenyapkan menghapuskan segala rasa hiba"],
    ["他在", "tā zài", "he inside", "apa yang ditanggung oleh dia di dalam jajaran"],
    ["采石场里", "cǎi shí chǎng lǐ", "inside stone quarry", "kawasan kuari memecah batu gergasi itu punya"],
    ["所遭受的", "suǒ zāo shòu de", "suffered", "segala penderitaan"],
    ["委屈", "wěi qu", "grievances", "rasa terkilan / penganiayaan kejam"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 7 段
    ["令人", "lìng rén", "Make people", "Menyebabkan setiap orang yang berfikir merasa tersangat"],
    ["匪夷所思的", "fěi yí suǒ sī de", "unimaginable", "hairan ajaib di luar jangkaan fikiran logal akal"],
    ["是", "shì", "is", "bahawa"],
    ["，", "", "", ""],
    ["自从有了", "zì cóng yǒu le", "ever since having", "semenjak dari saat wujudnya hadirnya buah"],
    ["这片菜园", "zhè piàn cài yuán", "this vegetable garden", "sebidang tapak kebun sayur ini punya jajaran"],
    ["之后", "zhī hòu", "after", "selepas itu kelak"],
    ["，", "", "", ""],
    ["整个监狱", "zhěng gè jiān yù", "the whole prison", "keseluruhan suasana isi penjara itu belaka"],
    ["有了很大的", "yǒu le hěn dà de", "had a very big", "telah mengalami suatu perubahan bentuk transformasi"],
    ["改观", "gǎi guān", "change", "perubahan corak wajah baru berseri"],
    ["：", "", "", ""],
    ["每到", "mĕi dào", "every time arriving at", "setiap kali menjelang tibanya waktu"],
    ["放风时间", "fàng fēng shí jiān", "exercise time", "keluar mengambil udara segar bersiar-siar harian"],
    ["，", "", "", ""],
    ["许多狱友", "xǔ duō yù  yǒu", "many fellow inmates", "ramai gila rakan-rakan banduan sekeliling belaka"], // 👈 中文数量“许多”不分开
    ["都会帮助他", "dōu huì bāng zhù tā", "all would help him", "pun pakat-kapat turun padang akan membantu menolong dia untuk"],
    ["来照料一下", "lái zhào liào yí xià", "to come take care a bit", "datang menyiram mencangkung menjaga sekejap jajaran baki"],
    ["满园的", "mǎn yuán de", "full garden's", "seluruh kawasan kebun itu punya buah sayur"],
    ["蔬菜", "shū cài", "vegetables", "sayur-sayuran segar hijau"],
    ["，", "", "", ""],
    ["在狱警们", "zài yù jǐng men", "under prison guards'", "di waktu mata warder-warder polis penjara itu所有"],
    ["不注意的时候", "bú zhù ý de shí hou", "not paying attention time", "lalai terlepas pandang tidak mengambil tumpuan perhatian waktu kala itu"],
    ["，", "", "", ""],
    ["他们还能", "tā men hái néng", "they also could", "mereka pun malah berupaya jua sempat curi-curi untuk"],
    ["揣几个", "chuāi jǐ gè", "hide a few", "menyembunyikan menyumbat beberapa biji buah"], // 👈 中文数量“几个”：不分开，填满
    ["番茄", "fān qié", "tomatoes", "tomato merah segar"],
    ["回去", "huí qù", "go back", "bawa balik masuk"],
    ["，", "", "", ""],
    ["以备", "yǐ bèi", "in order to prepare for", "demi sebagai bekalan makanan"],
    ["夜晚", "yè wǎn", "night time", "waktu malam hari gelap kelak di"],
    ["享用", "xiǎng yòng", "enjoy eating", "makan ratah nikmati dengan penuh lazat gembira"],
    ["。", "", "", ""],
    ["更令人", "gèng lìng rén", "Even more making people", "Malah yang jauh bertambah bertambah menyebabkan orang merasa tersangat"],
    ["称奇的", "chēng qí de", "marvel", "terpegun kagum pelik ajaib adalah sememangnya"],
    ["是", "shì", "is", "bahawa kedudukan jajaran"],
    ["，", "", "", ""],
    ["狱警们的", "yù jǐng men de", "prison guards'", "warder-warder polis penjara punya buah"],
    ["态度", "tài du", "attitudes", "ragam pembawaan kelakuan dan akhlak layanan harian"],
    ["似乎也", "sì hū yě", "seemingly also", "nampaknya seolah-olah pun turut sama jua"],
    ["变得", "biàn de", "became", "bertukar menjadi semakin"],
    ["和蔼多了", "hé ǎi duō le", "much more amiable", "lembut mesra dan bersopan-santun banyak gila gila sudah"],
    ["，", "", "", ""],
    ["因为他", "yīn wèi tā", "because he", "ini adalah kerana disebabkan dia sentiasa kekal"],
    ["总是把", "zǒng  shì bǎ", "always object particle", "sentiasa bertindak memastikan menyebabkan jajaran buah"],
    ["新采摘的", "xīn cǎi zhāi de", "newly picked", "tomato yang baru sahaja segar dipetik dahan punya buah"],
    ["番茄", "fān qié", "tomatoes", "tomato merah ranum itu"],
    ["发给", "fā gěi", "distributed to", "diagih-agihkan diserahkan terus kepada"],
    ["狱友们", "yù  yǒu men", "fellow cellmates", "rakan-rakan sekeliling sekongkol belaka"],
    ["，", "", "", ""],
    ["然后再由", "rán hòu zài yóu", "then furthermore by means of", "kemudian selepas itu barulah pula melalui perantara tangan"],
    ["狱友们", "yù  yǒu men", "fellow cellmates", "rakan-rakan banduan itu punya peranan sendiri untuk"],
    ["送到", "sòng dào", "delivered to", "dihantar diserahkan masuk ke dalam genggaman tangan"],
    ["狱警们手中", "yù jǐng men shǒu zhōng", "inside prison guards' hands", "warder-warder polis penjara tapak tangan di dalam"],
    ["。", "", "", ""],
    ["吃了", "chī le", "Eaten", "Apabila dah selesai kenyang makan menelan buah"],
    ["犯人的", "fàn rén de", "prisoner's", "banduan punya pemberian ikhlas buah"],
    ["番茄", "fān qié", "tomatoes", "tomato merah itu"],
    ["，", "", "", ""],
    ["狱警们", "yù jǐng men", "prison guards", "warder-warder polis penjara itu semua punya baki"],
    ["拿鞭子的", "ná biān zi de", "holding whip's", "tangan yang memegang cemeti cambuk kayu rotan punya"],
    ["手", "shǒu", "hand", "anggota tangan kekuasaan zalim itu"],
    ["，", "", "", ""],
    ["也不再那么", "yě bú zài nà me", "also no longer so", "pun sudah langsung tidak lagi berkeadaan sebegitu rupa ganas"],
    ["蛮横了", "mán hèng le", "tyrannical", "bengis, kasar kejam bersikap meluru-luru membabi buta dah"],
    ["。", "", "", ""],
    ["一个", "yí gè", "A / one", "Seorang korps tentera warder"], // 👈 中文数字“一个”不分开
    ["黑人狱警", "hēi rén  yù jǐng", "black prison guard", "polis penjara berbangsa kulit hitam"],
    ["说", "shuō", "said", "telah mengeluarkan testimoni berkata luahan rasa bahawa"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["每当", "mĕi dāng", "Every time when", "Setiap kali saban kali apabila diri saya secara gopoh"],
    ["我莽撞地", "wǒ mǎng zhuàng de", "I rashly", "secara meluru bodoh / kurang fikir dengan kasar"],
    ["举起", "jǔ qǐ", "raised up", "mengangkat mengacungkan tinggi-tinggi up"],
    ["鞭子的时候", "biān zi de shí hou", "whip's time", "tali cemeti rotan penyeksa waktu kala itu punya saat"],
    ["，", "", "", ""],
    ["我就想起了", "wǒ jiù xiǎng qǐ le", "I then remembered", "saya terus serta-merta teringat terbayang meresap akal akan bahawa"],
    ["这是一群", "zhè shì yì qún", "this is a group of", "mereka yang berada di depan saya ini表达群意其实是 sekelompok"], // 👈 中文数量“一群”不分开
    ["递给我", "dì gěi wǒ", "handed over to me", "manusia yang sering menghulurkan menyerahkan kepada saya punya"],
    ["番茄吃的人", "fān qié chī de rén", "people who give tomatoes", "manusia yang beri buah tomato untuk dimakan ratah segar"],
    ["，", "", "", ""],
    ["他们", "tā men", "they", "mereka jajaran banduan murni ini semua jua"],
    ["让我想起了", "ràng wǒ xiǎng qǐ le", "remind me of", "berjaya menyebabkan ingatan akal saya melayang teringat terbayang rindu akan"],
    ["自己的", "zì jǐ de", "oneself's", "diri own punya ahli"],
    ["家人", "jiā rén", "family members", "keluarga bapa emak isteri anak di rumah kampong"],
    ["，", "", "", ""],
    ["总是在我", "zǒng  shì zài wǒ", "always at my", "sentiasa kekal berada di saat waktu ketika diri saya berada dalam fasa"],
    ["最疲劳的时候", "zuì pí láo de shí hou", "most tired time", "tersangat keletihan letih lesu penat maung gila gila kala itu"],
    ["递给我", "dì gěi wǒ", "handed over to me", "sudi menghulurkan menyerahkan terus ke tangan saya buah"],
    ["新鲜的水果", "xīn xiān de shuǐ guǒ", "fresh fruits", "buahan yang tersangat segar bugar bervitamin"],
    ["……”", "", "", ""],

    ["\n", "", "", ""], // 👈 第 8 段
    ["囚犯", "qiú fàn", "Prisoners", "Golongan khalayak banduan"],
    ["和", "hé", "and", "dan juga pihak korps"],
    ["狱警们的关系", "yù jǐng men de guān xi", "prison guards' relationship", "warder polis penjara belaka punya ikatan silaturahim hubungan harian"],
    ["逐渐", "zhú jiàn", "gradually", "lama-kelamaan / perlahan-lahan bertukar"],
    ["融洽起来", "róng qià qǐ lái", "harmonious up", "menjadi tersangat mesra, harmoni rapat"],
    ["，", "", "", ""],
    ["这位", "zhè  wèi", "this", "tokoh yang satu ini punya susuk nama"],
    ["“第", "dì", "the (prefix for ordinal numbers)", "yang ke-"], // 👈 中文前缀：保留拼音翻译
    ["466", "", "", ""], // 👈 阿拉伯数字：分开且留空
    ["号囚犯”", "hào qiú fàn", "prisoner number", "banduan nombor"],
    ["，", "", "", ""],
    ["也在", "yě zài", "also inside", "pun turut sama di dalam pekarangan kurungan"],
    ["罗本岛监狱", "luó běn dǎo jiān  yù", "Robben Island Prison", "Penjara Pulau Robben itu"],
    ["整整", "zhěng zhěng", "solidly", "genap-genap tanpa kurang seharipun tempoh masa masa"],
    ["种了", "zhòng le", "cultivated", "berjaya berkebun mengusahakan tapak"],
    ["18", "", "", ""], // 👈 阿拉伯数字：分开且留空
    ["年", "nián", "years", "tahun"],
    ["的", "de", "particle", "punya sebidang"],
    ["菜园", "cài yuán", "vegetable garden", "kebun sayur hijau murni"],
    ["。", "", "", ""],
    ["这位", "zhè  wèi", "This", "Tokoh mulia yang satu ini punya susuk jajaran"],
    ["“第466号囚犯”", "", "", ""],
    ["不是别人", "bú  shì bié rén", "was not anyone else", "sememangnya bukannya mana-mana orang asing luar jua jua"],
    ["，", "", "", ""],
    ["正是", "zhèng  shì", "exactly was", "adalah merupakan tidak lain tidak bukan sosok pejuang gemilang"],
    ["黑人总统", "hēi rén zǒng tǒng", "black president", "Presiden Kulit Hitam agung negara Afrika Selatan iaitu"],
    ["曼德拉", "màn dé lā", "Mandela", "Nelson Mandela"],
    ["。", "", "", ""],
    ["曼德拉", "màn dé lā", "Mandela", "Nelson Mandela itu punya jajaran watak"],
    ["用", "yòng", "by using", "hanya dengan sekadar menggunakan modal modal"],
    ["几只番茄", "jǐ zhī fān qié", "a few tomatoes", "beberapa biji sahaja buah tomato merah pemberian ikhlas"], // 👈 中文数字“几只”：不分开，填满
    ["就让", "jiù ràng", "then made", "telah serta-merta berjaya menyebabkan menyebabkan整个"],
    ["整个监狱", "zhěng gè jiān yù", "the whole prison", "pekarangan isi dan penghuni penjara gergasi itu belaka"],
    ["变得", "biàn de", "became", "bertukar berubah wajah menjadi tersangat"],
    ["融洽起来", "róng qià qǐ lái", "harmonious up", "harmoni, mesra, aman damai rapat semula up"],
    ["，", "", "", ""],
    ["乍一看", "zhà yí kàn", "at first glance", "kalau dipandang jeling sekilas pada zahir luarannya sahaja"],
    ["，", "", "", ""],
    ["这是一件", "zhè shì yí jiàn", "this is a", "ini merupakan satu bonek perkara kerja kebajikan yang"], // 👈 中文数字“这是一件”不分开
    ["十分轻松的", "shí fēn qīng sōng de", "extremely easy's", "tersangat mudah, ringan remeh and 'relax' sahaja punya hal"],
    ["事情", "shì qing", "matter", "urusan perkara harian"],
    ["，", "", "", ""],
    ["其实", "qí shí", "actually", "namun pada hakikat kebenaran yang tersirat di sebaliknya adalah"],
    ["，", "", "", ""],
    ["曼德拉", "màn dé lā", "Mandela", "Nelson Mandela itu punya batin perbuatan"],
    ["哪里是在", "nǎ lǐ shì zài", "where on earth was currently inside", "bukanlah sekadar pada zahirnya sedang bertindak menguruskan"],
    ["经营菜园", "jīng yíng cài yuán", "operating vegetable garden", "mengusahakan menguruskan ladang kebun sayur semata-mata"],
    ["，", "", "", ""],
    ["他是在", "tā shì zài", "he was currently doing inside", "sebaliknya lubuk perbuatan dia adalah sedang bertindak gigih melakukan usaha"],
    ["耕作", "gēng zuò", "cultivating", "bercucuk tanam, membajak gembur tanah di sebidang bidang"],
    ["一片片", "yí piàn piàn", "piece after piece of", "setiap kepingan bidang bidang lapis"], // 👈 中文数字“一片片”不分开
    ["心灵的腹地", "xīn línɡ de fù dì", "soul's hinterland", "lubuk sanubari, tangki emosi kemanusiaan"],
    ["呀", "ya", "particle", "lah ya jua"],
    ["！", "", "", ""],

    ["\n", "", "", ""], // 👈 第 9 段
    ["一颗", "yì kē", "A", "Sekeping seulas ulas"], // 👈 中文数字“一颗”不分开
    ["乐观坚定的", "lè guān jiān dìng de", "optimistic and firm", "iman tekad semangat yang tersangat optimis ceria and teguh kencang punya"],
    ["心", "xīn", "heart", "lubuk hati sanubari manusia"],
    ["，", "", "", ""],
    ["即使是", "jí shǐ  shì", "even if it is", "walau dalam keadaan terpaksa dicampakkan tercampak berada"],
    ["身处", "shēn chǔ", "oneself is inside", "diri menetap menghuni mengharungi di dalam jajaran"],
    ["磨难重重的", "mó nàn chóng chóng de", "full of tribulations", "kawah denda sengsara penderitaan penyiksaan yang bertindih-tindih berlapis-lapis punya"],
    ["地狱", "dì yù", "hell", "lembah neraka jahanam denda dunianya"],
    ["，", "", "", ""],
    ["也能", "yě néng", "also can", "pun pasti akan berupaya berkuasa jua untuk bertindak"],
    ["开垦出", "kāi kěn chū", "cultivate out", "meneroka, mencangkul membajak melahirkan keluar mari sebuah"],
    ["一片", "yí piàn", "a stretch of", "sebidang pekarangan zon"], // 👈 中文数字“一片”不分开
    ["阳光明媚的", "yáng guāng míng mèi de", "sunny and splendid", "kawasan yang sarat dipenuhi limpahan cahaya matahari terang, indah gembira punya"],
    ["伊甸园来", "yī diàn yuán lái", "Eden garden out mari", "Taman Syurga Firdaus (Taman Eden) jua akhirnya mari keluar"],
    ["！", "", "", ""],

    ["\n", "", "", ""], // 👈 出处
    ["（", "", "", ""],
    ["李丹崖", "lǐ dān yá", "Li Danyai (Author)", "Li Danyai (Penulis)"],
    ["《", "", "", ""],
    ["曼德拉的", "màn dé lā de", "Mandela's", "Tomato"],
    ["番茄", "fān qié", "Tomatoes", "Nelson Mandela"],
    ["》", "", "", ""],
    ["，", "", "", ""],
    ["有", "yǒu", "with", "ada"],
    ["改动", "gǎi dòng", "adaptations", "ubah suai"],
    ["）", "", "", ""]
];
